#!/usr/bin/env python3
# -*- coding: utf-8 -*-


# ---------------------------------------------------------------------------------------------------------------------
# %% Imports

import torch
import torch.nn as nn

from .components.mask_decoder_transformer import MaskDecoderTransformer
from .components.shared import LayerNorm2d, UpscaleCT2x2Layer

# For type hints
from torch import Tensor


# ---------------------------------------------------------------------------------------------------------------------
# %% Classes


class SAMV3p1MaskDecoder(nn.Module):
    """
    Simplified implementation of the 'mask decoder' component described in:
        "SAM 3: Segment Anything with Concepts"
        By: Nicolas Carion∗, Laura Gustafson, Yuan-Ting Hu, Shoubhik Debnath, Ronghang Hu, Didac Suris, et al.
        @ https://arxiv.org/abs/2511.16719

    In v3.1, there are two similar, but not identical implementations of the mask decoder.
    One is used for 'interactive' masking (e.g. SAMv1 task) and the other for video
    segmentation (e.g. SAMv2 task). The video version is called the 'MultiplexMaskDecoder':
    https://github.com/facebookresearch/sam3/blob/bfbed072a07a6a52c8d5fdc75a7a186251a835b1/sam3/model/multiplex_mask_decoder.py#L16
    https://github.com/facebookresearch/sam3/blob/bfbed072a07a6a52c8d5fdc75a7a186251a835b1/sam3/sam/mask_decoder.py#L14

    To support the v3.1 updates, there is now a dedicated 'multiplex mask decoder' which wraps
    around this module. In the non-multiplex use case, this module behaves exactly the same as in
    SAMv3.0, however there are some minor 'toggle flags' added to this module to enable
    support for multiplexing

    In the v3.1 update, there are a number of small changes that complicate the implementation
    of the mask decoder. Most of these changes are related to the handling of 'multiplex' masks,
    which change the shape of many of the internal tensors.

    This model takes in image and prompt encodings and creates segmentation masks.
    Like the V2 implementation, the V3 mask decoder includes 'object' outputs
    (an object pointer and object score, used for video processing). It
    also includes extra processing of image encodings, which makes use of the
    hi-res image features generated by the V3 image projection model.

    In the original implementation, the non-multiplex variant of the model generates
    4 masks but only returns either 1 or 3 masks, based on whether many prompts were
    given (return only 1 mask) or only 1 point or box prompt was given (return 3 masks).
    In this implementation, the non-multiplex variant model always returns all 4 masks,
    and it is left up to the end user to decide what to do with them.

    The multiplex variant generates 3 masks (instead of 4) but additionally generates
    16 copies of these to support multiplexing, for a total of 48 (!) masks. For the
    sake of compatibility between variants (and prior SAM implementations), the
    multiplex variant moves the 16 multiplex copies into the batch dimension on output.
    """

    # .................................................................................................................

    def __init__(
        self,
        input_channels: int = 256,
        downsample_dim: int = 128,
        num_layers: int = 2,
        num_heads: int = 8,
        num_mask_tokens: int = 4,
        multiplex_channels: int = 1,
    ):

        # Inherit from parent
        super().__init__()

        # Check if multiplexing is enabled (e.g. for video-mask-decoding)
        is_mplex = multiplex_channels > 1

        # Set up model for handling input mask hints for improving segmentation results
        self.maskhint_encoder = MaskHintEncoderVideo() if is_mplex else MaskHintEncoderImage(input_channels)

        # Set up model to encode which mask entries are being multiplexed
        self.multiplex_encoder = (
            MultiplexEncoderVideo(input_channels, multiplex_channels) if is_mplex else MultiplexEncoderImage()
        )
        self._multiplex_mnc_shape = (multiplex_channels, num_mask_tokens, input_channels)

        # Set up cls-like embeddings, which are combined with prompt embeddings as input into transformer
        self.cls_obj_token = nn.Parameter(torch.empty(1, multiplex_channels, input_channels))
        self.cls_iou_token = nn.Parameter(torch.empty(1, multiplex_channels, input_channels))
        self.cls_mask_tokens = nn.Parameter(torch.empty(1, num_mask_tokens * multiplex_channels, input_channels))

        # Create transformer decoder
        self.transformer = MaskDecoderTransformer(num_layers, num_heads, input_channels, downsample_dim)

        # Create layers for generating final outputs
        self.maskgen = MaskGen(input_channels, num_mask_tokens)
        self.iou_token_mlp = MLP3Layers(input_channels, num_mask_tokens, use_sigmoid_output=True)
        self.objptrgen = ObjectPointerGen(input_channels, include_no_pointer_projection=is_mplex)

        # Special-case downsampler for making 'mask hints' used to produce object pointers from mask prompts
        self.mask_to_ptr_hint_downsampler = nn.Identity() if is_mplex else nn.Conv2d(1, 1, kernel_size=4, stride=4)

    # .................................................................................................................

    def forward(
        self,
        encoded_image_tokens_list_bchw: Tensor,
        encoded_prompts_bnc: Tensor,
        image_posenc_bchw: Tensor,
        mask_hint: Tensor | None = None,
        blank_promptless_output: bool = True,
        num_multiplex_objects: int = 1,
    ) -> tuple[Tensor, Tensor, Tensor, Tensor]:
        """
        Generates multiple candidate segmentation masks given an image encoding and
        encoded prompts (which specific the part of the image to segment).
        Also returns estimates for the 'quality' of each segmentation mask.

        The mask_hint input can be provided to help 'refine' the model output in some cases.
        It is expected to be of the same shape as a single mask output by the model. If
        the mask_hint argument is given as an integer, this is interpretted to mean to
        run the model twice, once to generate onc eset of masks and then to index out
        one of those masks to use as a hint for re-running the model.

        If 'blank_promptless_output' is true and no prompts are given, then a fully
        'blank' result will be returned instead of running the full decoder.

        The 'num_multiplex_objects' input is only for use with multiplexing
        (during video segmentation). It indicates how many of the built-in
        multiplex outputs (16 by default) are being used. Mask quality will
        be slightly degraded if there is a mismatch between this value and
        the 'true' mask count being used

        Returns:
            mask_predictions, iou_predictions, object_pointers, object_score
            -> Mask prediction has shape: BxNxHxW (N 'ambiguity' masks, 4 by default)
            -> IoU has shape: BxN
            -> Object pointer has shape: BxNxF (F is features per token, default 256)
            -> Object score has shape Bx1 and indicates (score > 0) if an object is masked
            -> Mask H & W are 4x the size of the image patch encoding size
            -> The 0-th mask was originally intended to be used in cases with
               many prompts, and not to be used with single points/box prompts
            -> Multiplexed outputs are stored in the batch (B) dimension!
        """

        # For clarity
        batch_size_prompts, num_prompts, enc_dim = encoded_prompts_bnc.shape
        lowres_tokens, hires_tokens_x2, hires_tokens_x4 = encoded_image_tokens_list_bchw
        batch_size_image = lowres_tokens.shape[0]

        # Handle batched inputs
        if batch_size_image > 1 or batch_size_prompts > 1:
            if batch_size_prompts == 1:
                encoded_prompts_bnc = encoded_prompts_bnc.expand(batch_size_image, -1, -1)
            if batch_size_image == 1:
                lowres_tokens = lowres_tokens.expand(batch_size_prompts, -1, -1, -1)
                hires_tokens_x2 = hires_tokens_x2.expand(batch_size_prompts, -1, -1, -1)
                hires_tokens_x4 = hires_tokens_x4.expand(batch_size_prompts, -1, -1, -1)
                image_posenc_bchw = image_posenc_bchw.expand(batch_size_prompts, -1, -1, -1)
            batch_size_prompts, batch_size_image = encoded_prompts_bnc.shape[0], lowres_tokens.shape[0]
            assert (
                batch_size_prompts == batch_size_image
            ), "Batch size mismatch! Cannot use different image/prompt batch sizes"

        # Concatenate learned 'cls' tokens, which will be prepended to prompts
        mask_tokens = self.multiplex_encoder(self.cls_mask_tokens, num_multiplex_objects)
        cls_tokens_bnc = torch.cat([self.cls_obj_token, self.cls_iou_token, mask_tokens], dim=1)
        cls_tokens_bnc = cls_tokens_bnc.expand(batch_size_prompts, -1, -1)

        # Figure out how to 'un-index' each of the concatenated cls_tokens
        num_obj_tokens, num_iou_tokens = self.cls_obj_token.shape[1], self.cls_iou_token.shape[1]
        slice_obj_tokens = slice(0, num_obj_tokens)
        slice_iou_tokens = slice(num_obj_tokens, num_obj_tokens + num_iou_tokens)
        slice_mask_tokens = slice(slice_iou_tokens.stop, cls_tokens_bnc.shape[1])

        # Cross-encode image tokens with prompt tokens
        img_tokens_bchw = self.maskhint_encoder(lowres_tokens, mask_hint)
        prompt_tokens = torch.cat((cls_tokens_bnc, encoded_prompts_bnc), dim=1)
        encoded_prompt_tokens, encoded_img_tokens = self.transformer(prompt_tokens, img_tokens_bchw, image_posenc_bchw)

        # Extract the (now-encoded) 'cls' tokens by undoing the earlier cls concatenation step
        obj_token_out = encoded_prompt_tokens[:, slice_obj_tokens, :]
        iou_token_out = encoded_prompt_tokens[:, slice_iou_tokens, :]
        mask_tokens_out = encoded_prompt_tokens[:, slice_mask_tokens, :]

        # Separate multiplex & ambiguity entries (takes shape from Bx(M*N)xC -to-> BxMxNxC)
        mask_tokens_bmnc = mask_tokens_out.view(batch_size_prompts, *self._multiplex_mnc_shape)

        # Produce final output mask & quality predictions
        mask_preds_bmnhw = self.maskgen(encoded_img_tokens, hires_tokens_x2, hires_tokens_x4, mask_tokens_bmnc)
        iou_preds_bmn = self.iou_token_mlp(iou_token_out)

        # Generate 'object score' and 'object pointer' outputs (meant for video segmentation)
        obj_score_bm1, obj_ptrs_bmnc = self.objptrgen(obj_token_out, mask_tokens_bmnc)

        # Combine batch and multiplex dimensions together for compatibility with SAMv1/v2/v3
        # -> Multiplexing is still supported as a batch operation this way
        mask_preds_mnhw = mask_preds_bmnhw.flatten(0, 1)
        iou_preds_mn = iou_preds_bmn.flatten(0, 1)
        obj_ptrs_mnc = obj_ptrs_bmnc.flatten(0, 1)
        obj_score_m1 = obj_score_bm1.flatten(0, 1)

        # Special case. Wipe out outputs if no prompt is given
        if blank_promptless_output and (num_prompts == 0) and (mask_hint is None):
            mask_preds_mnhw = 0 * mask_preds_mnhw - 100.0
            iou_preds_mn = 0 * iou_preds_mn
            obj_ptrs_mnc = 0 * obj_ptrs_mnc
            obj_score_m1 = 0 * obj_score_m1 - 10

        return mask_preds_mnhw, iou_preds_mn, obj_ptrs_mnc, obj_score_m1

    # .................................................................................................................

    @staticmethod
    def get_best_mask_index(iou_predictions: Tensor) -> Tensor:
        """Helper used to select the index of the 'best' output, based on the highest IoU prediction score"""
        return torch.argmax(iou_predictions, dim=-1)

    # .................................................................................................................

    @staticmethod
    def get_best_decoder_results(
        mask_preds: Tensor, iou_preds: Tensor, obj_ptrs: Tensor, exclude_0th_index: bool = True
    ) -> tuple[Tensor, Tensor, Tensor, Tensor]:
        """
        Helper used to keep only the 'best' result from the mask decoder predictions.
        The 'exclude_0th_index' flag is used to ignore the mask normally associated
        with 'multi-prompt' masking (which is stored in the 0th index of the results)

        Returns:
            best_index, best_mask_prediction, best_iou_score, best_object_pointer
            -> Best index is a tensor (!) with shape: B (i.e. 1 index for each batch entry)
            -> Mask prediction has shape: Bx1xHxW
            -> IoU has shape: Bx1
            -> Object pointer has shape: Bx1xF (F features, 256 by default)
        """

        # Use highest iou prediction as indicator of the 'best' results
        # -> Optionally exclude the 0th index, which is normally used when multiple-prompts are given
        best_idx = 1 + torch.argmax(iou_preds[:, 1:], dim=-1) if exclude_0th_index else torch.argmax(iou_preds, dim=-1)

        best_mask_pred = mask_preds[:, best_idx, :, :]
        best_iou_pred = iou_preds[:, best_idx]
        best_obj_ptr = obj_ptrs[:, best_idx, :]

        return best_idx, best_mask_pred, best_iou_pred, best_obj_ptr

    # .................................................................................................................


# ---------------------------------------------------------------------------------------------------------------------
# %% Model components


class MaskGen(nn.Module):
    """
    Sub-module of the SAM mask decoder which is responsible for generating the final output masks
    Performs upscaling of image embeddings (back to original input resolution) as well
    as a projection of encoder mask ('cls') tokens before dot-producting with image tokens
    to get final masks.

    Like the v2 implementation (but unlike SAMv1) the upscaling step involves additional
    hi-res copies of the encoded image tokens, which come from the image projection model.

    The original implementation was directly part of the mask decoder model. Here, it's been split
    out into it's own module for clarity. For the original implementation details see:
    https://github.com/facebookresearch/sam3/blob/bfbed072a07a6a52c8d5fdc75a7a186251a835b1/sam3/model/multiplex_mask_decoder.py#L333-L350
    https://github.com/facebookresearch/sam3/blob/bfbed072a07a6a52c8d5fdc75a7a186251a835b1/sam3/sam/mask_decoder.py#L226-L233
    """

    # .................................................................................................................

    def __init__(self, input_channels: int, num_mask_tokens: int):

        # Inherit from parent
        super().__init__()

        # Create model for handling image token upscaling
        upscaler_channels = input_channels // 8
        self.img_patch_upscaler = MaskUpscalerWithHiresSupport(input_channels, upscaler_channels)

        # Create model for further processing encoded mask 'cls' tokens
        self.mask_token_mlps = nn.ModuleList(
            [MLP3Layers(input_channels, upscaler_channels) for i in range(num_mask_tokens)]
        )

        # Create helper tensor for recording the model device/dtype information
        self.register_buffer("device_info", torch.empty(0), persistent=False)

    # .................................................................................................................

    def forward(
        self,
        lowres_image_tokens: Tensor,
        hires_tokens_x2: Tensor,
        hires_tokens_x4: Tensor,
        cls_mask_tokens_bmnc: Tensor,
    ) -> Tensor:
        """
        Produces (non-thresholded) segmentation masks based on
        the encoded image & mask token data from earlier
        transformer layers. The output contains multiple masks, which
        are meant to help cover ambiguity. The number of masks
        varies between multiplexed/non-multiplexed versions.
        The multiplexed variant also include 16 (by default) copies
        of each of the ambiguity masks!

        Returns:
            segmentation_masks
            -> shape: BxMxNxHxW
            -> B batch size
            -> M multiplex count (1 or 16 by default)
            -> N number of ambiguity masks (3 or 4 by default)
            -> H & W are based on the input image height & width
        """

        # Convert image tokens to 'image-like' shape and upscale them to final output size
        upscaled_img_tokens = self.img_patch_upscaler(lowres_image_tokens, hires_tokens_x2, hires_tokens_x4)

        # Further encode cls mask tokens
        encoded_mask_tokens_list = [mlp(cls_mask_tokens_bmnc[:, :, i, :]) for i, mlp in enumerate(self.mask_token_mlps)]
        encoded_mask_tokens = torch.stack(encoded_mask_tokens_list, dim=2)

        # Take dot product (along channel dimension) of cls tokens with image patches for final masks
        return torch.einsum("bmnc, bchw -> bmnhw", encoded_mask_tokens, upscaled_img_tokens)

    # .................................................................................................................


class MaskUpscalerWithHiresSupport(nn.Module):
    """
    Helper module used to handle mask upscaling while incorporating the
    hi-res image feature maps available from the output of the SAMv3 image projection model

    This module does not exist in the original implementation, which instead unpacks the
    existing sequential model and uses each component separately:
    https://github.com/facebookresearch/sam3/blob/bfbed072a07a6a52c8d5fdc75a7a186251a835b1/sam3/model/multiplex_mask_decoder.py#L317-L320
    https://github.com/facebookresearch/sam3/blob/bfbed072a07a6a52c8d5fdc75a7a186251a835b1/sam3/sam/mask_decoder.py#L221-L224
    """

    # .................................................................................................................

    def __init__(self, input_channels: int, output_channels: int):

        # Inherit from parent
        super().__init__()

        hidden_channels = input_channels // 4
        self.upscale_1 = UpscaleCT2x2Layer(input_channels, hidden_channels)
        self.norm = LayerNorm2d(hidden_channels)
        self.upscale_2 = UpscaleCT2x2Layer(hidden_channels, output_channels)
        self.gelu = nn.GELU()

    def forward(self, lowres_image_tokens: Tensor, hires_tokens_x2: Tensor, hires_tokens_x4: Tensor) -> Tensor:
        """
        Upscales the provided low-resolution image tokens (by a factor of 4),
        while incorporating the 2x hi-res and 4x hi-res features
        Returns:
            upscaled_4x_image_tokens
        """

        # Upscale once by a factor of 2, and include hires 2x tokens
        upscaled_tokens_x2 = self.upscale_1(lowres_image_tokens)
        upscaled_tokens_x2 = self.norm(upscaled_tokens_x2 + hires_tokens_x2)
        upscaled_tokens_x2 = self.gelu(upscaled_tokens_x2)

        # Upscale again by a factor of 2, and include hires 4x tokens
        upscaled_tokens_x4 = self.upscale_2(upscaled_tokens_x2)
        upscaled_tokens_x4 = self.gelu(upscaled_tokens_x4 + hires_tokens_x4)

        return upscaled_tokens_x4

    # .................................................................................................................


class MaskHintEncoderImage(nn.Module):
    """
    Sub-module of the mask decoder which is responsible for encoding input masks,
    which can act as a hint for where the output segmentation mask should be generated.
    If a hint isn't given, a learned 'no-mask' embedding will be used instead.

    This functionality was originally implemented as part of the prompt encoder,
    but structurally it's simpler if implemented as a component of the decoder model,
    mostly because it needs access to the image token shape, whereas the prompt encoder doesn't.

    The original implementation details can be found here:
    https://github.com/facebookresearch/sam3/blob/bfbed072a07a6a52c8d5fdc75a7a186251a835b1/sam3/sam/prompt_encoder.py#L54-L63
    """

    # .................................................................................................................

    def __init__(self, output_channels: int = 256):

        # Inherit from parent
        super().__init__()

        # Define a fall-back embedding to use when no mask hint is given
        self.no_mask_embed = nn.Parameter(torch.empty(1, output_channels))

        # For clarity. These values are hard-coded from original SAM implementation
        input_channels = 1
        num_hidden_ch_1 = 4
        num_hidden_ch_2 = 16
        self.downscaler = nn.Sequential(
            nn.Conv2d(input_channels, num_hidden_ch_1, kernel_size=2, stride=2),
            LayerNorm2d(num_hidden_ch_1),
            nn.GELU(),
            nn.Conv2d(num_hidden_ch_1, num_hidden_ch_2, kernel_size=2, stride=2),
            LayerNorm2d(num_hidden_ch_2),
            nn.GELU(),
            nn.Conv2d(num_hidden_ch_2, output_channels, kernel_size=1),
        )

        # Helper variable used to keep track of the model device/dtype (need for mask hints)
        self.register_buffer("device_info", torch.empty(1), persistent=False)

    # .................................................................................................................

    def forward(self, image_tokens_bchw: Tensor, mask_hint_bhw: Tensor | None) -> Tensor:
        """
        If a mask hint is provided, it will be encoded and added to the image tokens
        If a hint isn't given, then a learned 'no-mask' embedding is used instead.

        The mask hint should ideally be 4x the height & width of the patch grid,
        corresponding to the size of the outputs of the mask decoder itself
        -> This seems to be the original intended usage, to feed back output
           masks as prompts for refinement
        -> For example, with default (1008x1008px -> 72x72 tokens) sizing,
           the mask should be 288x288px

        Returns:
            hint_encoded_image_tokens_bchw
            -> Same shape as input image tokens (BxCxHxW)
        """

        # Create no-mask embedding if no hint is provided otherwise process mask to form encoded embedding
        grid_h, grid_w = image_tokens_bchw.shape[2:]
        if mask_hint_bhw is None:
            encoded_mask_hint = self.no_mask_embed.reshape(1, -1, 1, 1).expand(1, -1, grid_h, grid_w)

        else:
            # Add batch dimension to incoming mask, if needed
            if mask_hint_bhw.ndim == 2:
                mask_hint_bhw = mask_hint_bhw.unsqueeze(0)

            # Encode hint and scale to target size if needed
            encoded_mask_hint = self.downscaler(mask_hint_bhw.to(self.device_info))
            _, _, hint_h, hint_w = encoded_mask_hint.shape
            if hint_h != grid_h or hint_w != grid_w:
                encoded_mask_hint = nn.functional.interpolate(encoded_mask_hint, size=(grid_h, grid_w))

        return image_tokens_bchw + encoded_mask_hint

    # .................................................................................................................


class MaskHintEncoderVideo(nn.Module):
    """
    Helper variant, used on the 'video' mask decoder, which doesn't support mask hint inputs
    This implementation doesn't do anything and exists only for compatibility with the 'image' variant of the decoder
    """

    # .................................................................................................................

    def __init__(self, output_channels: int | None = None):
        super().__init__()

    def forward(self, image_tokens_bchw: Tensor, mask_hint_bhw: None = None) -> Tensor:
        """Returns: image_tokens_bchw (unchanged)"""
        if mask_hint_bhw is not None:
            raise ValueError("Cannot use mask hints when video masking!")
        return image_tokens_bchw

    # .................................................................................................................


class ObjectPointerGen(nn.Module):
    """
    Helper module of the SAMV3 mask decoder. This module handles the
    computation of object pointers and the 'object score', which are
    generated from encoded mask tokens and the encoded object token,
    respectively, from the mask decoder.

    For original implementation, see:
    https://github.com/facebookresearch/sam3/blob/bfbed072a07a6a52c8d5fdc75a7a186251a835b1/sam3/model/video_tracking_multiplex.py#L884-L895
    """

    # .................................................................................................................

    def __init__(self, features_per_token: int = 256, include_no_pointer_projection: bool = True):

        # Inherit from parent
        super().__init__()

        # Create 'no pointer' projection, used to encode pointers when no objects present
        self.no_ptr_proj = nn.Identity()
        if include_no_pointer_projection:
            self.no_ptr_proj = nn.Linear(features_per_token, features_per_token)

        # Projection layers to convert encoded tokens to score & pointer
        self.score_mlp = MLP3Layers(features_per_token, 1)
        self.pointer_mlp = MLP3Layers(features_per_token, features_per_token)

    # .................................................................................................................

    def forward(self, object_token_bmc: Tensor, encoded_mask_tokens_bmnc: Tensor) -> tuple[Tensor, Tensor]:
        """
        Produces an object score and object pointer from encoded tokens
        from the mask decoder.

        The object score is a single number which indicates how likely
        it is that a segmentated object is 'present'. This is meant for
        use with video segmentation, where the model is 'auto-prompting'
        and may not always segment an object. The score will typically be
        +5 or more when an object is present and take on negative values
        when there is no object.

        The object pointer is a 'memory' representation of the object,
        used to help to continue to segment the same object on future
        frames when running on videos. It's used by the memory fusion
        model. There is one pointer for each mask token (4 by default).

        Returns:
            object_score, object_pointers
            -> score shape is: Bx1
            -> pointer shape is: Bx4xF
            -> For B batch size, F features per token (256 by default)
        """

        # Compute object score & pointers
        objscore_bm1 = self.score_mlp(object_token_bmc)
        objptrs_bmnc = self.pointer_mlp(encoded_mask_tokens_bmnc)

        # Perform extra filtering of pointers based on object score, see:
        # https://github.com/facebookresearch/sam3/blob/bfbed072a07a6a52c8d5fdc75a7a186251a835b1/sam3/model/video_tracking_multiplex.py#L884-L895
        is_valid_bm11 = (objscore_bm1 > 0)[:, :, :, None].to(dtype=encoded_mask_tokens_bmnc.dtype)
        objptrs_bmnc = (objptrs_bmnc * is_valid_bm11) + (self.no_ptr_proj(objptrs_bmnc) * (1.0 - is_valid_bm11))

        return objscore_bm1, objptrs_bmnc

    # .................................................................................................................


class MultiplexEncoderVideo(nn.Module):
    """
    Helper module for the 'video' variant of the mask-decoder used in SAMv3.1

    In this variant, the cls mask tokens require a special additive embedding
    prior to encoding through the mask decoder transformer. This embedding
    is used to indicate which mask entries are being used with multiplexing
    vs. unused entries.

    In the original code, the logic for this operation is spread across multiple
    files. For the original implementation logic, see:
    https://github.com/facebookresearch/sam3/blob/bfbed072a07a6a52c8d5fdc75a7a186251a835b1/sam3/model/video_tracking_multiplex.py#L791-L801
    https://github.com/facebookresearch/sam3/blob/bfbed072a07a6a52c8d5fdc75a7a186251a835b1/sam3/model/multiplex_mask_decoder.py#L267-L273
    """

    # .................................................................................................................

    def __init__(self, features_per_token: int = 256, multiplex_channels: int = 16):

        # Inherit from parent
        super().__init__()

        # Embeddings used to represent 'active' and 'inactive' multiplex indexes
        self.embed_active = nn.Parameter(torch.empty((1, multiplex_channels, 1, features_per_token)))
        self.embed_inactive = nn.Parameter(torch.empty((1, multiplex_channels, 1, features_per_token)))

    def forward(self, mask_tokens_bnc: Tensor, num_active_multiplex: int = 1):

        # Build embedding that encodes which mask entries are being used for multiplexing
        # -> We assume that active entries are always stored in first N indexes
        activity_offset_1m1c = torch.concat(
            (self.embed_active[:, :num_active_multiplex, :, :], self.embed_inactive[:, num_active_multiplex:, :, :]),
            dim=1,
        )

        # Tokens are given in BxN'xC format, but N' is a combination of multiplex (M) and
        # the number of ambiguity masks (3 by default). The activity embeddings are shared
        # for all ambiguity entries, so we need to reshape BxN'xC -> BxMxNxC, then add
        # embeddings, then flatten back to BxN'xC
        mask_b, mask_n, mask_c = mask_tokens_bnc.shape
        num_total_multiplex = activity_offset_1m1c.shape[1]
        mask_tokens_bmnc = mask_tokens_bnc.view(mask_b, num_total_multiplex, mask_n // num_total_multiplex, mask_c)
        out_tokens_bnc = (mask_tokens_bmnc + activity_offset_1m1c).flatten(1, 2)

        return out_tokens_bnc

    # .................................................................................................................


class MultiplexEncoderImage(nn.Module):
    """
    Helper module for the 'image' variant of the mask-decoder used in SAMv3.1
    This variant does nothing! It's used for compatibility with the video implementation
    """

    def forward(self, mask_tokens_bnc: Tensor, num_active_multiplex: int = 1):
        return mask_tokens_bnc

    # .................................................................................................................


class MLP3Layers(nn.Module):
    """
    Simplified implementation of the 3-layer MLP model used by the mask-decoder of SAM:
    https://github.com/facebookresearch/sam3/blob/bfbed072a07a6a52c8d5fdc75a7a186251a835b1/sam3/model/multiplex_mask_decoder.py#L448
    https://github.com/facebookresearch/sam3/blob/bfbed072a07a6a52c8d5fdc75a7a186251a835b1/sam3/sam/mask_decoder.py#L299

    Simple 3-layer linear/feed-forward network using relu activations on layer 1 & 2,
    the final layer does not apply an activation function. All layers have dimensions equal to
    the input dimension, except the very last layer which is sized to the output dimension
    (i.e. dimension doesn't change through layers 1 & 2)
    """

    # .................................................................................................................

    def __init__(self, input_channels: int, output_channels: int, use_sigmoid_output: bool = False):

        # Inherit from parent
        super().__init__()

        self.layers = nn.Sequential(
            nn.Linear(input_channels, input_channels),
            nn.ReLU(),
            nn.Linear(input_channels, input_channels),
            nn.ReLU(),
            nn.Linear(input_channels, output_channels),
            nn.Sigmoid() if use_sigmoid_output else nn.Identity(),
        )

    def forward(self, tokens_BNC: Tensor) -> Tensor:
        """MLP acting on 'rows-of-tokens' with shape: BxNxC, output may have different channel count: BxNxCout"""
        return self.layers(tokens_BNC)

    # .................................................................................................................
